server_addr: "easy.echosite.cn:4443"
trust_host_root_certs: false
echosite_id: "18683958697"
echosite_token: "$2y$10$Dq7v2rY5MA423fDvq7SiYOIecVzX6S3GFOkixclWLW9CNIGCQsavm"
tunnels:
  name1:
    subdomain: "xing"
    proto:
        http:
          127.0.0.1:5000